### ISSUE TITLE
fig.yml compatibility?

### ISSUE THREAD

**Issue by dimaip** [modera/mcloud#22]
Hey awesome product there, but why inventing the wheel and not making mcloud.yml compatible with format of fig.yml?
Some discrepancies like `environment` vs `env` are really strange...

**Comment by ribozz** [comment]
Good point. I think, in scope of this ticket we should also check other differences with fig.yml.
If it's really minor like env <-> environment, then we should add aliases, because lot of production servers run with current syntax already. 
Sure we can't make it 100% compatible. As some things are not needed in scope of mcloud, and thereis some things missing in fig.yml.

**Comment by ribozz** [comment]
Another point:
fig is deprecated, now it is Commpose, spec for yml file is here:
http://docs.docker.com/compose/yml/

**Comment by dimaip** [comment]
Maybe if you support all the main features of Compose, you could actually make mcloud.yml format backward-compatible with Compose?
That's an important thing, as those fig.yml things have quickly become a de-facto standard for defining your services...

**Comment by ribozz** [comment]
Compose has wider scope, so have less restrictive permissions and have wider range of options that may be tuned up.
mcloud goal is to run application securely without modifications of configs in dev and production.

Quick overview of things that are not compatible now:

*volumes* - we don't allow to mount volumes from outside of application directory
*volumes_from* - not allowed, can be implemented by mapping same dir to multiple containers
*links* - we don't need links (echa container can reach another in scope of same application).
*ports* - not needed. Only http ports are mapped and handled by load balancer. Other ports can be used without any restrictions in scope of one app
*expose* - same as ports
*environment* - alias needed
*env_file* - missing feature
*net* - not needed. Mcloud is responsible for configuring network
*dns* - same as net
*cap_add*, *cap_drop* - not used for security reasons.
*dns_search* - used internally by mcloud, not allowed to change
*working_dir*, *entrypoint* - supported (not sure that exact same name)
*user* - not allowed to change, managed by mcloud
*hostname* - also managed by mcloud
*mem_limit*, *cpu_shares* - assigned internaly, same as FS quata, trafic quota, cpu quota
*priviledged* - not allowed for security reasons
*restart* - missing feature
*stdin_open*, *tty* - managed by mcloud
*command* - need alias

Already compatible:
* image
* build

Can be made compatible:
- command
- environment
- env_file
- working_dir
- restart

**Comment by dimaip** [comment]
Thanks for explaining your reasoning behind this, I see the point now.
I may return to mcloud once I need something more advanced than what I have now.
