### ISSUE TITLE
How to link containers in mcloud.yml?

### ISSUE THREAD

**Issue by dimaip** [modera/mcloud#23]
My images depend on each other, e.g. on some env variables set in other images. How do I link them in mcloud.yml?

**Comment by ribozz** [comment]
Can you provide some examples how you use ENV variables.
In fig, environment variables a heavily used to resolve other service ip. But in mcloud
it solved through DNS, so not needed.
Any other examples of how ENV is used? 
We can then see if it can be solved other way that is native for mcloud.

**Comment by dimaip** [comment]
Yeah, I use it as sort of ancient service discovery. I understand it's not the most advanced technique, but I don't want to re-work the docker image just for mcloud now.
Actually I've given up with mcloud (in favor of simple nginx reverse proxy + fig) for now because of its incompatibility with fig/compose, as it's an important factor for me now -- I want my images to remain fig-friendly.

See here for example usage: https://github.com/dimaip/docker-typo3-flow-neos-abstract/blob/master/container-files/build-typo3-app/include-variables.sh

**Comment by ribozz** [comment]
Solution for you that will work both in mcloud and Fig:

T3APP_DB_HOST=${T3APP_DB_HOST:="mysql"}
T3APP_DB_PORT=${T3APP_DB_PORT:="3306"}

If you link containers, Fig will be able to resolve "mysql" (or how you call your container?).

**Comment by dimaip** [comment]
Oh, good to know it works this way in mcloud too.
